"""Test all three new tools: WebSearch, arXiv, MarkdownWriter."""

import sys
sys.path.insert(0, "/home/jinxu/tiny-agents")

from tiny_agents.tools import WebSearchTool, ArxivTool, MarkdownWriterTool

def test_arxiv():
    print("\n=== Test: ArxivTool ===")
    tool = ArxivTool()
    result = tool.execute({"query": "LoRA vision transformer fine-tuning", "max_results": 5})
    print(f"  success: {result.success}")
    if result.success:
        papers = result.output["papers"]
        print(f"  found {len(papers)} papers")
        for p in papers[:2]:
            print(f"  - {p['title'][:60]}...")
            print(f"    authors: {', '.join(p['authors'][:3])}")
    else:
        print(f"  ERROR: {result.error}")
    return result.success

def test_websearch():
    print("\n=== Test: WebSearchTool ===")
    tool = WebSearchTool()  # No API key → uses DuckDuckGo fallback
    result = tool.execute({"query": "LoRA vision model fine-tuning 2024", "num_results": 3})
    print(f"  success: {result.success}")
    if result.success:
        results = result.output["results"]
        print(f"  engine: {result.output['engine']}")
        print(f"  found {len(results)} results")
        for r in results[:2]:
            print(f"  - {r['title'][:60]}")
    else:
        print(f"  ERROR: {result.error}")
    return result.success

def test_markdown_writer():
    print("\n=== Test: MarkdownWriterTool ===")
    tool = MarkdownWriterTool(default_output_dir="/home/jinxu/tiny-agents/output")
    content = """# Test Report

This is a test report generated by the MarkdownWriterTool.

## Section 1

Some content here.

## References

1. Author, A. (2024). *Title*. Journal.
"""
    result = tool.execute({"content": content, "filename": "test_report.md", "mode": "write"})
    print(f"  success: {result.success}")
    if result.success:
        print(f"  written to: {result.output['filepath']}")
        print(f"  lines: {result.output['lines_written']}")
    else:
        print(f"  ERROR: {result.error}")
    return result.success

if __name__ == "__main__":
    results = {}
    results["arxiv"] = test_arxiv()
    results["websearch"] = test_websearch()
    results["markdown"] = test_markdown_writer()

    print("\n=== Summary ===")
    for name, ok in results.items():
        print(f"  {name}: {'✅ PASS' if ok else '❌ FAIL'}")
    sys.exit(0 if all(results.values()) else 1)
